export const UPLOAD_FILES = 'UPLOAD_FILES';
export const UPLOAD_FILES_START = `${UPLOAD_FILES}_START`;
export const UPLOAD_FILES_SUCCESS = `${UPLOAD_FILES}_SUCCESS`;
export const UPLOAD_FILES_FAILED = `${UPLOAD_FILES}_FAILED`;
export const UPLOAD_FILES_PROGRESS = `${UPLOAD_FILES}_PROGRESS`;
